//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::users::Entity as Users;
pub use super::videos::Entity as Videos;
pub use super::views::Entity as Views;
pub use super::watches::Entity as Watches;
