// Code generated by "stringer -type=EnvKey"; DO NOT EDIT.

package utils

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DATA_ROOT-0]
	_ = x[DB_HOST-1]
	_ = x[DB_PORT-2]
	_ = x[DB_USER-3]
	_ = x[DB_PASSWORD-4]
	_ = x[DB_NAME-5]
	_ = x[AUTH_API_SECRET-6]
	_ = x[AUTH_TOKEN_LIFESPAN_HRS-7]
}

const _EnvKey_name = "DATA_ROOTDB_HOSTDB_PORTDB_USERDB_PASSWORDDB_NAMEAUTH_API_SECRETAUTH_TOKEN_LIFESPAN_HRS"

var _EnvKey_index = [...]uint8{0, 9, 16, 23, 30, 41, 48, 63, 86}

func (i EnvKey) String() string {
	if i < 0 || i >= EnvKey(len(_EnvKey_index)-1) {
		return "EnvKey(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnvKey_name[_EnvKey_index[i]:_EnvKey_index[i+1]]
}
