version: "3"
services:
  server:
    image: "streamfox/server"
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: docker/prod/server.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8801:8801"
    environment:
      GIN_MODE: release
      APP_DATA_ROOT: /streamfox/data
      APP_PORT: 8801
      DB_HOST: postgres

  postgres:
    image: postgres
    restart: unless-stopped
    hostname: postgres
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
