[package]
name = "entity"
version = "0.0.0"
edition = "2021"

[dependencies]
bs58 = { version = "0.5.0", default-features = false, features = ["alloc"] }
sea-orm = { version = "0.12.14", default-features = false }
serde = { version = "1.0.196", default-features = false, features = ["derive"] }
