name: Prod Docker Image CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build:
    name: Build
    runs-on:
      - ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          file: "docker/prod/server.Dockerfile"
